Updated s2i scripts

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,2 +1,16 @@
 cp -R /tmp/src /opt/app-root/
-cd /opt/app-root/src && gradle build
+cd /opt/app-root/src
+
+echo "---->>>> Building application with Gradle"
+gradle build
+
+ARTIFACT_DIR=${ARTIFACT_DIR:-build/libs}
+
+echo "--> # ARTIFACT_DIR = $ARTIFACT_DIR"
+echo "---> Rename artifact $(find $ARTIFACT_DIR -name *.jar)"
+result_file=$(find $ARTIFACT_DIR -name *.jar)
+if [ -z "$result_file" ]; then
+  echo "---> Build file could not be found"
+  exit 1
+fi
+mv $result_file app.jar
